export const policyIds = [
  "random",
  "greedy",
  "epsilon-greedy",
  "decaying-epsilon-greedy",
  "softmax",
  "gradient-bandit",
  "ucb",
  "kl-ucb",
  "moss",
  "bernoulli-thompson-sampling",
  "gaussian-thompson-sampling",
  "bernoulli-bayesian-ucb",
  "gaussian-bayesian-ucb",
  "sliding-window-ucb",
  "discounted-ucb",
  "sliding-window-bernoulli-thompson-sampling",
  "discounted-bernoulli-thompson-sampling",
  "change-point-ucb",
  "cusum-ucb",
  "page-hinkley-ucb",
  "successive-elimination",
  "median-elimination",
  "exp3",
  "linear-epsilon-greedy",
  "linucb",
  "linear-thompson-sampling",
  "logistic-contextual-bandit",
] as const;

export type PolicyId = (typeof policyIds)[number];
export type PolicyFamily =
  "foundations" | "optimism" | "bayesian" | "changing" | "best-arm" | "adversarial" | "contextual";
export type EnvironmentKind =
  | "stationary-bernoulli"
  | "stationary-gaussian"
  | "changing-bernoulli"
  | "best-arm"
  | "adversarial"
  | "contextual-linear"
  | "contextual-logistic";
export type PolicyObjective = "cumulative-reward" | "best-arm";
export type ParameterValue = number | boolean | string | null;
export type ParameterValues = Record<string, ParameterValue>;

export interface ParameterDefinition {
  key: string;
  label: string;
  shortLabel?: string;
  kind: "number" | "integer" | "boolean" | "select" | "optional-number";
  minimum?: number;
  maximum?: number;
  step?: number;
  options?: readonly { value: string; label: string }[];
  advanced?: boolean;
  help: string;
}

export interface PolicyDefinition {
  id: PolicyId;
  className: string;
  label: string;
  family: PolicyFamily;
  environment: EnvironmentKind;
  objective: PolicyObjective;
  badge: string;
  title: string;
  intro: string;
  defaults: ParameterValues;
  guidedParameters: ParameterValues;
  parameters: readonly ParameterDefinition[];
  guidedSeed: number;
  challengeSeed: number;
  horizon: number;
  challengeHorizon: number;
  target: string;
}

export const familyOrder: readonly PolicyFamily[] = [
  "foundations",
  "optimism",
  "bayesian",
  "changing",
  "best-arm",
  "adversarial",
  "contextual",
];

export const familyDefinitions: Record<
  PolicyFamily,
  { number: string; label: string; title: string; description: string }
> = {
  foundations: {
    number: "01",
    label: "Foundations",
    title: "The Ancient Gates",
    description: "Compare direct exploration rules on a stationary set of portals.",
  },
  optimism: {
    number: "02",
    label: "Optimism",
    title: "The Observatory",
    description: "See how confidence bounds turn uncertainty into a reason to explore.",
  },
  bayesian: {
    number: "03",
    label: "Bayesian methods",
    title: "The Oracle Vault",
    description: "Watch prior beliefs become posterior decisions as rewards arrive.",
  },
  changing: {
    number: "04",
    label: "Changing environments",
    title: "The Shifting Tides",
    description: "Test policies that forget old evidence or detect abrupt changes.",
  },
  "best-arm": {
    number: "05",
    label: "Best arm identification",
    title: "The Trial Grounds",
    description: "Spend a fixed sampling budget to identify the strongest portal.",
  },
  adversarial: {
    number: "06",
    label: "Adversarial rewards",
    title: "The Trickster's Arena",
    description: "Learn from partial feedback when rewards do not come from fixed probabilities.",
  },
  contextual: {
    number: "07",
    label: "Contextual bandits",
    title: "The Labyrinth of Signals",
    description: "Use Light, Echo, and Tide to make a different decision each round.",
  },
};

const initialValue: ParameterDefinition = {
  key: "initial_value",
  label: "Initial estimate",
  shortLabel: "Q₀",
  kind: "number",
  minimum: -2,
  maximum: 2,
  step: 0.1,
  help: "The estimate assigned to every portal before the first observation.",
};
const epsilon: ParameterDefinition = {
  key: "epsilon",
  label: "Exploration chance",
  shortLabel: "ε",
  kind: "number",
  minimum: 0,
  maximum: 1,
  step: 0.01,
  help: "The chance of choosing a random portal.",
};
const learningRate: ParameterDefinition = {
  key: "learning_rate",
  label: "Learning rate",
  shortLabel: "η",
  kind: "number",
  minimum: 0.01,
  maximum: 1,
  step: 0.01,
  help: "How strongly one observation changes the learned state.",
};
const ucbC: ParameterDefinition = {
  key: "c",
  label: "Confidence scale",
  shortLabel: "c",
  kind: "number",
  minimum: 0.05,
  maximum: 5,
  step: 0.05,
  help: "How strongly the policy favors uncertain portals.",
};
const rewardScale: ParameterDefinition = {
  key: "reward_scale",
  label: "Reward noise bound",
  shortLabel: "R",
  kind: "number",
  minimum: 0.05,
  maximum: 3,
  step: 0.05,
  help: "The reward scale used in the confidence bonus.",
};
const alphaPrior: ParameterDefinition = {
  key: "alpha_prior",
  label: "Prior successes",
  shortLabel: "α₀",
  kind: "number",
  minimum: 0.1,
  maximum: 10,
  step: 0.1,
  help: "The Beta prior's initial success count.",
};
const betaPrior: ParameterDefinition = {
  key: "beta_prior",
  label: "Prior failures",
  shortLabel: "β₀",
  kind: "number",
  minimum: 0.1,
  maximum: 10,
  step: 0.1,
  help: "The Beta prior's initial failure count.",
};
const priorMean: ParameterDefinition = {
  key: "prior_mean",
  label: "Prior mean",
  shortLabel: "μ₀",
  kind: "number",
  minimum: -3,
  maximum: 3,
  step: 0.1,
  help: "The Gaussian mean assumed before any rewards are observed.",
};
const priorPrecision: ParameterDefinition = {
  key: "prior_precision",
  label: "Prior precision",
  shortLabel: "τ₀",
  kind: "number",
  minimum: 0.1,
  maximum: 10,
  step: 0.1,
  help: "How concentrated the Gaussian prior is.",
};
const observedPrecision: ParameterDefinition = {
  key: "reward_precision",
  label: "Reward precision",
  shortLabel: "τ",
  kind: "number",
  minimum: 0.1,
  maximum: 10,
  step: 0.1,
  help: "The assumed precision of observed Gaussian rewards.",
};
const quantile: ParameterDefinition = {
  key: "quantile",
  label: "Posterior quantile",
  shortLabel: "q",
  kind: "number",
  minimum: 0.5,
  maximum: 0.999,
  step: 0.001,
  help: "The posterior quantile used as the optimistic score.",
};
const windowSize: ParameterDefinition = {
  key: "window_size",
  label: "Window size",
  shortLabel: "w",
  kind: "integer",
  minimum: 1,
  maximum: 200,
  step: 1,
  help: "How many recent global rounds remain in memory.",
};
const discountFactor: ParameterDefinition = {
  key: "discount_factor",
  label: "Discount factor",
  shortLabel: "γ",
  kind: "number",
  minimum: 0.01,
  maximum: 0.99,
  step: 0.01,
  help: "How much evidence from earlier rounds is retained.",
};
const delta: ParameterDefinition = {
  key: "delta",
  label: "Failure probability",
  shortLabel: "δ",
  kind: "number",
  minimum: 0.01,
  maximum: 0.99,
  step: 0.01,
  help: "The allowed probability of an incorrect best portal result.",
};
const l2: ParameterDefinition = {
  key: "l2",
  label: "L2 regularization",
  shortLabel: "λ",
  kind: "number",
  minimum: 0,
  maximum: 5,
  step: 0.05,
  help: "The strength of coefficient shrinkage or matrix regularization.",
};

const cumulativeTarget = "Collect rewards while keeping expected regret under the target.";
const changingTarget = "Adapt after the portals change and keep expected regret under the target.";

function policy(
  definition: Omit<PolicyDefinition, "horizon" | "challengeHorizon" | "target"> &
    Partial<Pick<PolicyDefinition, "horizon" | "challengeHorizon" | "target">>,
): PolicyDefinition {
  return {
    horizon: 20,
    challengeHorizon: 30,
    target: cumulativeTarget,
    ...definition,
  };
}

export const policyCatalog: Record<PolicyId, PolicyDefinition> = Object.fromEntries(
  [
    policy({
      id: "random",
      className: "RandomPolicy",
      label: "Random",
      family: "foundations",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "uniform",
      title: "The Unmarked Compass",
      intro:
        "RandomPolicy gives every portal the same chance on every round. It is the baseline that learning policies should beat.",
      defaults: {},
      guidedParameters: {},
      parameters: [],
      guidedSeed: 101,
      challengeSeed: 1101,
    }),
    policy({
      id: "greedy",
      className: "GreedyPolicy",
      label: "Greedy",
      family: "foundations",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "argmax",
      title: "The First Favor",
      intro:
        "GreedyPolicy always follows its highest current estimate. Early luck can decide what it sees next.",
      defaults: { initial_value: 0 },
      guidedParameters: { initial_value: 0.5 },
      parameters: [initialValue],
      guidedSeed: 102,
      challengeSeed: 1102,
    }),
    policy({
      id: "epsilon-greedy",
      className: "EpsilonGreedyPolicy",
      label: "ε-greedy",
      family: "foundations",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "ε",
      title: "The Three Ancient Gates",
      intro:
        "Each round offers the same three gates. The policy chooses between its current estimates and a random test.",
      defaults: { initial_value: 0, epsilon: 0.1 },
      guidedParameters: { initial_value: 0, epsilon: 0.2 },
      parameters: [epsilon, initialValue],
      guidedSeed: 42,
      challengeSeed: 7,
      horizon: 12,
      challengeHorizon: 20,
      target: "Collect 12 relics while keeping expected regret at or below 3.25.",
    }),
    policy({
      id: "decaying-epsilon-greedy",
      className: "DecayingEpsilonGreedyPolicy",
      label: "Decaying ε-greedy",
      family: "foundations",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "ε(t)",
      title: "The Fading Lantern",
      intro: "Exploration starts high, then follows a visible schedule toward a chosen minimum.",
      defaults: { initial_value: 0, initial_epsilon: 1, min_epsilon: 0.01, decay_rate: 0.01 },
      guidedParameters: {
        initial_value: 0,
        initial_epsilon: 0.8,
        min_epsilon: 0.05,
        decay_rate: 0.2,
      },
      parameters: [
        { ...epsilon, key: "initial_epsilon", label: "Initial exploration chance" },
        { ...epsilon, key: "min_epsilon", label: "Minimum exploration chance" },
        { ...learningRate, key: "decay_rate", label: "Decay rate", minimum: 0 },
        initialValue,
      ],
      guidedSeed: 104,
      challengeSeed: 1104,
    }),
    policy({
      id: "softmax",
      className: "SoftmaxPolicy",
      label: "Softmax",
      family: "foundations",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "softmax",
      title: "The Heated Compass",
      intro:
        "SoftmaxPolicy turns estimates into sampling probabilities. Temperature controls how sharply it favors the leader.",
      defaults: { initial_value: 0, temperature: 1 },
      guidedParameters: { initial_value: 0, temperature: 0.35 },
      parameters: [
        {
          key: "temperature",
          label: "Temperature",
          shortLabel: "T",
          kind: "number",
          minimum: 0.05,
          maximum: 3,
          step: 0.05,
          help: "Higher values spread choices more evenly.",
        },
        initialValue,
      ],
      guidedSeed: 105,
      challengeSeed: 1105,
    }),
    policy({
      id: "gradient-bandit",
      className: "GradientBanditPolicy",
      label: "Gradient bandit",
      family: "foundations",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "H",
      title: "The Preference Forge",
      intro:
        "GradientBanditPolicy learns action preferences directly and samples from their softmax probabilities.",
      defaults: { learning_rate: 0.1, use_baseline: true },
      guidedParameters: { learning_rate: 0.1, use_baseline: true },
      parameters: [
        learningRate,
        {
          key: "use_baseline",
          label: "Use average reward baseline",
          kind: "boolean",
          help: "Subtract the running average reward before updating preferences.",
        },
      ],
      guidedSeed: 106,
      challengeSeed: 1106,
    }),
    policy({
      id: "ucb",
      className: "UCBPolicy",
      label: "UCB",
      family: "optimism",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "Q + bonus",
      title: "The Confidence Telescope",
      intro:
        "UCB adds an uncertainty bonus to each reward estimate and opens every unseen portal first.",
      defaults: { initial_value: 0, c: 2, reward_scale: 1 },
      guidedParameters: { initial_value: 0, c: 1, reward_scale: 1 },
      parameters: [ucbC, rewardScale, initialValue],
      guidedSeed: 201,
      challengeSeed: 1201,
    }),
    policy({
      id: "kl-ucb",
      className: "KLUCBPolicy",
      label: "KL-UCB",
      family: "optimism",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "KL",
      title: "The Divergence Lens",
      intro:
        "KL-UCB builds a Bernoulli confidence index from relative entropy rather than a square-root bonus.",
      defaults: { initial_value: 0, c: 3, tolerance: 0.000001, max_iterations: 32 },
      guidedParameters: { initial_value: 0, c: 3, tolerance: 0.000001, max_iterations: 32 },
      parameters: [
        ucbC,
        initialValue,
        {
          key: "tolerance",
          label: "Solver tolerance",
          kind: "number",
          minimum: 1e-9,
          maximum: 0.01,
          step: 1e-6,
          advanced: true,
          help: "The stopping tolerance for each KL index search.",
        },
        {
          key: "max_iterations",
          label: "Maximum solver iterations",
          kind: "integer",
          minimum: 1,
          maximum: 256,
          step: 1,
          advanced: true,
          help: "The maximum binary-search steps for one index.",
        },
      ],
      guidedSeed: 202,
      challengeSeed: 1202,
    }),
    policy({
      id: "moss",
      className: "MOSSPolicy",
      label: "MOSS",
      family: "optimism",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "MOSS",
      title: "The Horizon Glass",
      intro: "MOSS uses the known run horizon to scale exploration for a minimax regret objective.",
      defaults: { initial_value: 0, c: 1, reward_scale: 1 },
      guidedParameters: { initial_value: 0, c: 1, reward_scale: 1 },
      parameters: [ucbC, rewardScale, initialValue],
      guidedSeed: 203,
      challengeSeed: 1203,
    }),
    policy({
      id: "bernoulli-thompson-sampling",
      className: "BernoulliThompsonSamplingPolicy",
      label: "Bernoulli Thompson sampling",
      family: "bayesian",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "Beta draw",
      title: "The Coin Oracle",
      intro:
        "The policy draws one plausible success rate from each Beta posterior and follows the largest draw.",
      defaults: { alpha_prior: 1, beta_prior: 1 },
      guidedParameters: { alpha_prior: 1, beta_prior: 1 },
      parameters: [alphaPrior, betaPrior],
      guidedSeed: 301,
      challengeSeed: 1301,
    }),
    policy({
      id: "gaussian-thompson-sampling",
      className: "GaussianThompsonSamplingPolicy",
      label: "Gaussian Thompson sampling",
      family: "bayesian",
      environment: "stationary-gaussian",
      objective: "cumulative-reward",
      badge: "Normal draw",
      title: "The Bell Oracle",
      intro: "The policy samples a plausible mean for each portal from a Gaussian posterior.",
      defaults: { prior_mean: 0, prior_precision: 1, reward_precision: 1 },
      guidedParameters: { prior_mean: 0, prior_precision: 1, reward_precision: 1 },
      parameters: [priorMean, priorPrecision, observedPrecision],
      guidedSeed: 302,
      challengeSeed: 1302,
    }),
    policy({
      id: "bernoulli-bayesian-ucb",
      className: "BernoulliBayesianUCBPolicy",
      label: "Bernoulli Bayesian UCB",
      family: "bayesian",
      environment: "stationary-bernoulli",
      objective: "cumulative-reward",
      badge: "Beta q",
      title: "The Upper Prophecy",
      intro: "This policy scores each Bernoulli posterior by an optimistic upper quantile.",
      defaults: { alpha_prior: 1, beta_prior: 1, quantile: 0.95 },
      guidedParameters: { alpha_prior: 1, beta_prior: 1, quantile: 0.95 },
      parameters: [alphaPrior, betaPrior, quantile],
      guidedSeed: 303,
      challengeSeed: 1303,
    }),
    policy({
      id: "gaussian-bayesian-ucb",
      className: "GaussianBayesianUCBPolicy",
      label: "Gaussian Bayesian UCB",
      family: "bayesian",
      environment: "stationary-gaussian",
      objective: "cumulative-reward",
      badge: "Normal q",
      title: "The Credible Summit",
      intro: "This policy chooses the largest upper quantile from Gaussian posterior beliefs.",
      defaults: { prior_mean: 0, prior_precision: 1, reward_precision: 1, quantile: 0.95 },
      guidedParameters: { prior_mean: 0, prior_precision: 1, reward_precision: 1, quantile: 0.95 },
      parameters: [priorMean, priorPrecision, observedPrecision, quantile],
      guidedSeed: 304,
      challengeSeed: 1304,
    }),
    policy({
      id: "sliding-window-ucb",
      className: "SlidingWindowUCBPolicy",
      label: "Sliding-window UCB",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "window",
      title: "The Short Memory",
      intro:
        "Only observations from the most recent global rounds contribute to estimates and confidence.",
      defaults: { initial_value: 0, c: 2, reward_scale: 1, window_size: 100 },
      guidedParameters: { initial_value: 0, c: 1, reward_scale: 1, window_size: 8 },
      parameters: [windowSize, ucbC, rewardScale, initialValue],
      guidedSeed: 401,
      challengeSeed: 1401,
      horizon: 30,
      challengeHorizon: 40,
      target: changingTarget,
    }),
    policy({
      id: "discounted-ucb",
      className: "DiscountedUCBPolicy",
      label: "Discounted UCB",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "γⁿ",
      title: "The Fading Record",
      intro:
        "Every update discounts earlier counts and rewards before adding the newest observation.",
      defaults: { initial_value: 0, c: 2, reward_scale: 1, discount_factor: 0.9 },
      guidedParameters: { initial_value: 0, c: 2, reward_scale: 1, discount_factor: 0.9 },
      parameters: [discountFactor, ucbC, rewardScale, initialValue],
      guidedSeed: 402,
      challengeSeed: 1402,
      horizon: 30,
      challengeHorizon: 40,
      target: changingTarget,
    }),
    policy({
      id: "sliding-window-bernoulli-thompson-sampling",
      className: "SlidingWindowBernoulliThompsonSamplingPolicy",
      label: "Sliding-window Bernoulli TS",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "Beta window",
      title: "The Recent Oracle",
      intro: "Beta posteriors are rebuilt from observations still inside the global time window.",
      defaults: { alpha_prior: 1, beta_prior: 1, window_size: 100 },
      guidedParameters: { alpha_prior: 1, beta_prior: 1, window_size: 8 },
      parameters: [windowSize, alphaPrior, betaPrior],
      guidedSeed: 403,
      challengeSeed: 1403,
      horizon: 30,
      challengeHorizon: 40,
      target: changingTarget,
    }),
    policy({
      id: "discounted-bernoulli-thompson-sampling",
      className: "DiscountedBernoulliThompsonSamplingPolicy",
      label: "Discounted Bernoulli TS",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "Beta γⁿ",
      title: "The Fading Oracle",
      intro:
        "Success and failure evidence shrinks every round so recent outcomes carry more weight.",
      defaults: { alpha_prior: 1, beta_prior: 1, discount_factor: 0.95 },
      guidedParameters: { alpha_prior: 1, beta_prior: 1, discount_factor: 0.95 },
      parameters: [discountFactor, alphaPrior, betaPrior],
      guidedSeed: 404,
      challengeSeed: 1404,
      horizon: 30,
      challengeHorizon: 40,
      target: changingTarget,
    }),
    policy({
      id: "change-point-ucb",
      className: "ChangePointUCBPolicy",
      label: "Change-point UCB",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "alarm",
      title: "The Watcher's Bell",
      intro:
        "A selectable detector watches each portal and resets local evidence after a detected change.",
      defaults: {
        initial_value: 0,
        c: 2,
        reward_scale: 1,
        detector: "cusum",
        threshold: 5,
        drift: 0.05,
        min_observations: 20,
      },
      guidedParameters: {
        initial_value: 0,
        c: 1,
        reward_scale: 1,
        detector: "cusum",
        threshold: 1,
        drift: 0.02,
        min_observations: 4,
      },
      parameters: [
        {
          key: "detector",
          label: "Change detector",
          kind: "select",
          options: [
            { value: "cusum", label: "CUSUM" },
            { value: "page_hinkley", label: "Page-Hinkley" },
          ],
          help: "The per-portal detector used to trigger a reset.",
        },
        {
          key: "threshold",
          label: "Alarm threshold",
          kind: "number",
          minimum: 0.1,
          maximum: 20,
          step: 0.1,
          help: "Evidence required before a change alarm fires.",
        },
        {
          key: "drift",
          label: "Allowed drift",
          kind: "number",
          minimum: 0,
          maximum: 1,
          step: 0.01,
          help: "Small residual changes ignored by the detector.",
        },
        {
          key: "min_observations",
          label: "Minimum observations",
          kind: "integer",
          minimum: 1,
          maximum: 100,
          step: 1,
          help: "Per-portal observations required before detection begins.",
        },
        ucbC,
        rewardScale,
        initialValue,
      ],
      guidedSeed: 405,
      challengeSeed: 1405,
      horizon: 36,
      challengeHorizon: 45,
      target: changingTarget,
    }),
    policy({
      id: "cusum-ucb",
      className: "CUSUMUCBPolicy",
      label: "CUSUM UCB",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "CUSUM",
      title: "The Cumulative Alarm",
      intro:
        "CUSUM tracks positive and negative residual sums and resets a portal after a threshold crossing.",
      defaults: {
        initial_value: 0,
        c: 2,
        reward_scale: 1,
        threshold: 5,
        drift: 0.05,
        min_observations: 20,
      },
      guidedParameters: {
        initial_value: 0,
        c: 1,
        reward_scale: 1,
        threshold: 1,
        drift: 0.02,
        min_observations: 4,
      },
      parameters: [
        {
          key: "threshold",
          label: "Alarm threshold",
          kind: "number",
          minimum: 0.1,
          maximum: 20,
          step: 0.1,
          help: "Evidence required before a CUSUM alarm fires.",
        },
        {
          key: "drift",
          label: "Allowed drift",
          kind: "number",
          minimum: 0,
          maximum: 1,
          step: 0.01,
          help: "Small residual changes ignored by the detector.",
        },
        {
          key: "min_observations",
          label: "Minimum observations",
          kind: "integer",
          minimum: 1,
          maximum: 100,
          step: 1,
          help: "Per-portal observations required before detection begins.",
        },
        ucbC,
        rewardScale,
        initialValue,
      ],
      guidedSeed: 406,
      challengeSeed: 1406,
      horizon: 36,
      challengeHorizon: 45,
      target: changingTarget,
    }),
    policy({
      id: "page-hinkley-ucb",
      className: "PageHinkleyUCBPolicy",
      label: "Page-Hinkley UCB",
      family: "changing",
      environment: "changing-bernoulli",
      objective: "cumulative-reward",
      badge: "PH",
      title: "The Running Minimum",
      intro:
        "Page-Hinkley compares cumulative residual evidence with its running minimum before resetting a portal.",
      defaults: {
        initial_value: 0,
        c: 2,
        reward_scale: 1,
        threshold: 5,
        drift: 0.05,
        min_observations: 20,
      },
      guidedParameters: {
        initial_value: 0,
        c: 1,
        reward_scale: 1,
        threshold: 1,
        drift: 0.02,
        min_observations: 4,
      },
      parameters: [
        {
          key: "threshold",
          label: "Alarm threshold",
          kind: "number",
          minimum: 0.1,
          maximum: 20,
          step: 0.1,
          help: "Evidence required before a Page-Hinkley alarm fires.",
        },
        {
          key: "drift",
          label: "Allowed drift",
          kind: "number",
          minimum: 0,
          maximum: 1,
          step: 0.01,
          help: "Small residual changes ignored by the detector.",
        },
        {
          key: "min_observations",
          label: "Minimum observations",
          kind: "integer",
          minimum: 1,
          maximum: 100,
          step: 1,
          help: "Per-portal observations required before detection begins.",
        },
        ucbC,
        rewardScale,
        initialValue,
      ],
      guidedSeed: 407,
      challengeSeed: 1407,
      horizon: 36,
      challengeHorizon: 45,
      target: changingTarget,
    }),
    policy({
      id: "successive-elimination",
      className: "SuccessiveEliminationPolicy",
      label: "Successive elimination",
      family: "best-arm",
      environment: "best-arm",
      objective: "best-arm",
      badge: "active set",
      title: "The Narrowing Trial",
      intro: "Confidence intervals remove portals that can no longer plausibly be best.",
      defaults: { delta: 0.05, confidence_scale: 1 },
      guidedParameters: { delta: 0.2, confidence_scale: 0.3 },
      parameters: [
        delta,
        {
          key: "confidence_scale",
          label: "Confidence radius scale",
          kind: "number",
          minimum: 0.05,
          maximum: 3,
          step: 0.05,
          help: "Scales the elimination confidence radii.",
        },
      ],
      guidedSeed: 501,
      challengeSeed: 1501,
      horizon: 60,
      challengeHorizon: 80,
      target: "Recommend the true best portal within the sampling budget.",
    }),
    policy({
      id: "median-elimination",
      className: "MedianEliminationPolicy",
      label: "Median elimination",
      family: "best-arm",
      environment: "best-arm",
      objective: "best-arm",
      badge: "median",
      title: "The Halving Trial",
      intro: "The policy samples in phases and removes portals below the phase median.",
      defaults: { epsilon: 0.1, delta: 0.05 },
      guidedParameters: { epsilon: 0.8, delta: 0.5 },
      parameters: [
        {
          ...epsilon,
          minimum: 0.01,
          label: "Accuracy tolerance",
          help: "The allowed gap from the best portal.",
        },
        delta,
      ],
      guidedSeed: 502,
      challengeSeed: 1502,
      horizon: 60,
      challengeHorizon: 80,
      target: "Recommend the true best portal within the sampling budget.",
    }),
    policy({
      id: "exp3",
      className: "EXP3Policy",
      label: "EXP3",
      family: "adversarial",
      environment: "adversarial",
      objective: "cumulative-reward",
      badge: "EXP3",
      title: "The Trickster's Arena",
      intro:
        "EXP3 maintains multiplicative weights and learns from an importance-weighted reward estimate.",
      defaults: { gamma: 0.07, learning_rate: null },
      guidedParameters: { gamma: 0.2, learning_rate: null },
      parameters: [
        {
          key: "gamma",
          label: "Uniform mixing",
          shortLabel: "γ",
          kind: "number",
          minimum: 0.01,
          maximum: 1,
          step: 0.01,
          help: "The share of uniform exploration mixed into action probabilities.",
        },
        {
          key: "learning_rate",
          label: "Learning rate override",
          shortLabel: "η",
          kind: "optional-number",
          minimum: 0.01,
          maximum: 1,
          step: 0.01,
          help: "Leave blank to use gamma as the learning rate.",
        },
      ],
      guidedSeed: 601,
      challengeSeed: 1601,
      horizon: 30,
      challengeHorizon: 40,
    }),
    policy({
      id: "linear-epsilon-greedy",
      className: "LinearEpsilonGreedyPolicy",
      label: "Linear ε-greedy",
      family: "contextual",
      environment: "contextual-linear",
      objective: "cumulative-reward",
      badge: "xᵀθ or ε",
      title: "The Signal Explorer",
      intro:
        "A linear reward model learns from context while epsilon keeps a direct random exploration path.",
      defaults: { epsilon: 0.1, learning_rate: 0.1 },
      guidedParameters: { epsilon: 0.1, learning_rate: 0.1 },
      parameters: [epsilon, learningRate],
      guidedSeed: 701,
      challengeSeed: 1701,
    }),
    policy({
      id: "linucb",
      className: "LinUCBPolicy",
      label: "LinUCB",
      family: "contextual",
      environment: "contextual-logistic",
      objective: "cumulative-reward",
      badge: "xᵀθ + bonus",
      title: "The Labyrinth of Signals",
      intro:
        "Light, Echo, and Tide change each round. LinUCB combines a learned reward with an uncertainty bonus.",
      defaults: { alpha: 1, l2: 1 },
      guidedParameters: { alpha: 1, l2: 1 },
      parameters: [
        {
          key: "alpha",
          label: "Confidence width",
          shortLabel: "α",
          kind: "number",
          minimum: 0.05,
          maximum: 4,
          step: 0.05,
          help: "How strongly LinUCB values uncertain context directions.",
        },
        { ...l2, minimum: 0.05 },
      ],
      guidedSeed: 31415,
      challengeSeed: 20260824,
      horizon: 12,
      challengeHorizon: 20,
      target: "Collect 10 relics while keeping expected regret at or below 3.25.",
    }),
    policy({
      id: "linear-thompson-sampling",
      className: "LinearThompsonSamplingPolicy",
      label: "Linear Thompson sampling",
      family: "contextual",
      environment: "contextual-linear",
      objective: "cumulative-reward",
      badge: "xᵀθ draw",
      title: "The Sampled Signal",
      intro:
        "The policy samples a plausible coefficient vector for each portal before scoring the current signals.",
      defaults: { exploration_scale: 1, l2: 1 },
      guidedParameters: { exploration_scale: 1, l2: 1 },
      parameters: [
        {
          key: "exploration_scale",
          label: "Exploration scale",
          kind: "number",
          minimum: 0.05,
          maximum: 4,
          step: 0.05,
          help: "Scales posterior uncertainty in coefficient samples.",
        },
        { ...l2, minimum: 0.05 },
      ],
      guidedSeed: 703,
      challengeSeed: 1703,
    }),
    policy({
      id: "logistic-contextual-bandit",
      className: "LogisticContextualBanditPolicy",
      label: "Logistic contextual bandit",
      family: "contextual",
      environment: "contextual-logistic",
      objective: "cumulative-reward",
      badge: "sigmoid",
      title: "The Signal Odds",
      intro:
        "A logistic model predicts a bounded reward probability for every portal and signal pattern.",
      defaults: { epsilon: 0.05, learning_rate: 0.1, l2: 0 },
      guidedParameters: { epsilon: 0.05, learning_rate: 0.1, l2: 0 },
      parameters: [epsilon, learningRate, l2],
      guidedSeed: 704,
      challengeSeed: 1704,
    }),
  ].map((item) => [item.id, item]),
) as Record<PolicyId, PolicyDefinition>;

export const policiesByFamily = Object.fromEntries(
  familyOrder.map((family) => [
    family,
    policyIds.map((id) => policyCatalog[id]).filter((item) => item.family === family),
  ]),
) as Record<PolicyFamily, PolicyDefinition[]>;

export function isPolicyId(value: string): value is PolicyId {
  return (policyIds as readonly string[]).includes(value);
}
